export default {
  UPDATE_CITIES: 'UPDATE_CITIES',
  UPDATE_STATES: 'UPDATE_STATES',
  UPDATE_ZIP_CODES: 'UPDATE_ZIP_CODES',
  UPDATE_GEO_LOCATIONS: 'UPDATE_GEO_LOCATIONS',
  CLEAR_ALL_FILTERS: 'CLEAR_ALL_FILTERS'
}